routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Route;

Route::get('/', IndexController::class)->name('index');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::resource('post', PostController::class);



    Route::resource('category', CategoryController::class);

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Support\Str;

/**
 * Class Post
 * @package App\Models
 * @method paginate(int $count)

 */
class Post extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'body', 'img_url'];

    protected $appends = ['body_preview'];

    public function resolveRouteBinding($value, $field = null): ?Model
    {
        return $this->where('slug', $value)->orWhere($field ?? $this->getRouteKeyName(), $value)->firstOrFail();
    }
    /**
     * @return BelongsToMany
     */
    public function categories(): BelongsToMany
    {
        return $this->belongsToMany(Category::class, 'post_category');
    }

    /**
     * @return BelongsTo
     */
    public function author(): BelongsTo
    {
        return $this->belongsTo(User::class,  'author_id');
    }

    public function getBodyPreviewAttribute()
    {
        return Str::limit($this->body, 150);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Events\PostCreated;
use App\Http\Requests\TestRequest;
use App\Http\Requests\UpdatePostRequest;
use App\Http\Resources\TestResource;
use App\Models\Post;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

/**
 * @group Post management
 *
 * APIs for managing posts
 */
class PostController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @unauthenticated
     * @param  Request  $request
     * @return JsonResponse|Response
     */
    public function index(Request $request)
    {
        $posts = Post::query()->select(['id'])->paginate(12);
        if ($request->wantsJson()) {
            return TestResource::collection($posts);
        }
        return response()->view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return response()->view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @authenticated
     * @bodyParam title string required The post title.
     * @bodyParam body string required The post body.
     * @bodyParam img_url string The post image url.
     * @param  Request  $request
     * @return JsonResponse
     */
    public function store(Request $request): JsonResponse
    {


        $validated = $request->validate([
            'title' => 'required|unique:posts,title|max:255',
            'body' => 'required',
            'img_url' => ['nullable', 'url']
        ]);

        $request->user()->posts()->create($validated);

//        PostCreated::dispatch($request->user());

        return \response()->json(['ok']);
    }

    /**
     * Display the specified resource.
     *
     * @urlParam post string required The ID or Slug of the post. Example: 1
     *
     * @response {
     *  "id": 4,
     *  "name": "Jessica Jones",
     *  "roles": ["admin"]
     * }
     *
     *
     * @param  Post  $post
     * @return JsonResponse|Response
     */
    public function show(Post $post, Request $request): JsonResponse|Response
    {
        if ($request->wantsJson()) {
            return response()->json(['data' => $post]);
        }
        return response()->view('posts.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Post  $post
     * @return Response
     */
    public function edit(Post $post): Response
    {
        return response()->view('posts.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @authenticated
     * @urlParam post string required The post id or slug. Example: 1
     * @bodyParam title string The post title.
     * @bodyParam body string The post body.
     * @bodyParam img_url string The post image url.
     * @param  Request  $request
     * @param  Post  $post
     * @return JsonResponse|RedirectResponse
     */
    public function update(UpdatePostRequest $request, Post $post): JsonResponse|RedirectResponse
    {

        $validated = $request->validated();

        $post->update($validated);

        if ($request->wantsJson()) {
            return response()->json(['data' => $post]);
        }
        return redirect()->route('post.show', $post->slug);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Post  $post
     * @return Response
     */
    public function destroy(Post $post)
    {
        //
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mx-auto px-4">
        <div class="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-xl rounded-lg -mt-64">
            <div class="px-6">
                <div class="flex flex-wrap justify-start">
                    <div class="w-full lg:w-2/12 px-4 -mb-12">
                        <div class="py-6 px-3 mt-32 sm:mt-0">
                            <a href="{{ url()->previous() }}"
                               class="w-full block ring-2 ring-indigo-500 active:bg-pink-600 px-2 py-1 bg-white text-center text-black hover:shadow-md hover:bg-indigo-500 hover:text-white shadow rounded outline-none focus:outline-none sm:mr-2 mb-1"
                               type="button">
                                Back
                            </a>
                        </div>
                    </div>
                </div>
                <div class="mt-12 px-6">
                    <div class="md:grid md:grid-cols-3 md:gap-6">

                        <div class="mt-5 md:mt-0 md:col-span-3">
                            <form action="{{route('post.store')}}" method="POST">
                                @method('PUT')
                                @csrf
                                <div class="shadow sm:rounded-md sm:overflow-hidden">
                                    <div class="px-4 py-5 bg-white space-y-6 sm:p-6">
                                        <div class="grid grid-cols-3 gap-6">


                                            <div class="col-span-3 sm:col-span-2">
                                                <label for="title"
                                                                                         class="block text-sm font-medium text-gray-700">
                                                    Title
                                                </label>
                                                <div class="mt-1 flex rounded-md shadow-sm">
                                                    <input type="text"
                                                           name="title"
                                                           id="title"
                                                           value="{{old($post->title)}}"
                                                           class="focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded sm:text-sm border-gray-300">
                                                </div>
                                            </div>


                                            <div class="col-span-3 sm:col-span-2">
                                                <label for="img_url"
                                                       class="block text-sm font-medium text-gray-700">
                                                    Image url
                                                </label>
                                                <div class="mt-1 flex rounded-md shadow-sm">
                                                      <span
                                                          class="inline-flex items-center px-3 rounded-l-md border border-r-0 border-gray-300 bg-gray-50 text-gray-500 text-sm">
                                                            <i class="fas fa-image"></i>
                                                      </span>
                                                    <input type="text" name="img_url" id="img_url"
                                                           class="focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded-none rounded-r-md sm:text-sm border-gray-300"
                                                           value="https://picsum.photos/640/400/?random">
                                                </div>
                                            </div>
                                        </div>

                                        <div>
                                            <label for="body" class="block text-sm font-medium text-gray-700">
                                                Post body
                                            </label>
                                            <div class="mt-1">
                                                <textarea id="body" name="body" oninput="auto_grow(this)" rows="32"
                                                          class="max-h-full h-32  shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm border-gray-300 rounded-md"
                                                          placeholder="you@example.com">
                                                           {{old($post->body)}}
                                                </textarea>
                                            </div>

                                        </div>
                                    </div>
                                    <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                                        <button type="submit"
                                                class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                                            Save
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mx-auto px-4">
        <div class="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-xl rounded-lg -mt-64">
            <div class="px-6">
                <div class="flex flex-wrap justify-start">
                    <div class="w-full lg:w-2/12 px-4 -mb-12">
                        <div class="py-6 px-3 mt-32 sm:mt-0">
                            <a href="{{ url()->previous() }}"
                               class="w-full block ring-2 ring-indigo-500 active:bg-pink-600 px-2 py-1 bg-white text-center text-black hover:shadow-md hover:bg-indigo-500 hover:text-white shadow rounded outline-none focus:outline-none sm:mr-2 mb-1"
                               type="button">
                                Back
                            </a>
                        </div>
                    </div>
                </div>
                <div class="mt-12 px-6">
                    <div class="md:grid md:grid-cols-3 md:gap-6">

                        <div class="mt-5 md:mt-0 md:col-span-3">
                            <form action="{{route('post.update', $post->id)}}" method="POST">
                                @method('PUT')
                                @csrf
                                <div class="shadow sm:rounded-md sm:overflow-hidden">
                                    <div class="px-4 py-5 bg-white space-y-6 sm:p-6">
                                        <div class="grid grid-cols-3 gap-6">


                                            <div class="col-span-3 sm:col-span-2">
                                                <label for="title"
                                                                                         class="block text-sm font-medium text-gray-700">
                                                    Title
                                                </label>
                                                <div class="mt-1 flex rounded-md shadow-sm">
                                                    <input type="text"
                                                           name="title"
                                                           id="title"
                                                           value="{{old($post->title) ?? $post->title}}"
                                                           class="focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded sm:text-sm border-gray-300">
                                                </div>
                                            </div>


                                            <div class="col-span-3 sm:col-span-2">
                                                <label for="img_url"
                                                       class="block text-sm font-medium text-gray-700">
                                                    Image url
                                                </label>
                                                <div class="mt-1 flex rounded-md shadow-sm">
                                                      <span
                                                          class="inline-flex items-center px-3 rounded-l-md border border-r-0 border-gray-300 bg-gray-50 text-gray-500 text-sm">
                                                            <i class="fas fa-image"></i>
                                                      </span>
                                                    <input type="text" name="img_url" id="img_url"
                                                           class="focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded-none rounded-r-md sm:text-sm border-gray-300"
                                                           value="https://picsum.photos/640/400/?random">
                                                </div>
                                            </div>
                                        </div>

                                        <div>
                                            <label for="body" class="block text-sm font-medium text-gray-700">
                                                Post body
                                            </label>
                                            <div class="mt-1">
                                                <textarea id="body" name="body" oninput="auto_grow(this)" rows="32"
                                                          class="max-h-full h-32  shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm border-gray-300 rounded-md"
                                                          placeholder="you@example.com">
                                                           {{old($post->body) ?? $post->body}}
                                                </textarea>
                                            </div>

                                        </div>
                                    </div>
                                    <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                                        <button type="submit"
                                                class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                                            Save
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mx-auto px-4">
        <div class="flex flex-wrap items-center py-5 mt-32 bg-white overflow-hidden shadow sm:rounded-t-lg ">
            @foreach($posts as $post)
                <div
                    class="w-full sm:w-6/12 lg:w-4/12 px-4 mr-auto ml-auto opacity-75 transform transition duration-500 hover:opacity-100">
                    <div
                        class="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-lg rounded-lg bg-white"
                    >
                        <a href="{{route('post.show', $post->slug)}}">
                            <img
                                alt="{{$post->title}}"
                                src="{{$post->img_url.'='.$post->id}}"
                                class="w-full align-middle rounded-t-lg"
                            />
                        </a>
                        <blockquote class="relative p-8 pt-0 mb-4">
                            <svg
                                preserveAspectRatio="none"
                                xmlns="http://www.w3.org/2000/svg"
                                viewBox="0 0 583 95"
                                class="absolute left-0 w-full block"
                                style="height: 95px; top: -94px;"
                            >
                                <polygon
                                    points="584,95 -30,95  583,65"
                                    class="text-white fill-current"
                                ></polygon>
                            </svg>
                            <a href="{{route('post.show', $post->slug)}}">
                                <h4 class="text-xl font-bold text-black text-right">
                                    {{$post->title}}
                                </h4>
                            </a>
                            <div class="flex align-bottom flex-col leading-none">
                                <div class="flex flex-row justify-between items-center">
                                    <a class="flex items-center no-underline hover:underline text-black" href="#">
                                        <img alt="{{$post->author->name}}" class="block rounded-full"
                                             src="https://i.pravatar.cc/50?u={{$post->author->id}}">
                                        <span class="ml-2 text-sm"> {{$post->author->name}} </span>
                                    </a>
                                </div>
                            </div>
                            <p class="text-md font-light mt-2 text-black">
                                {{\Illuminate\Support\Str::limit($post->body, 150)}}
                            </p>
                        </blockquote>
                        <ul class="flex flex-row p-4 pt-0 text-gray-600 flex-wrap">
                            @foreach($post->categories as $category)
                                <li class="py-1">
                                    <div
                                        class="transition duration-300 ease-in-out rounded-2xl mr-1 px-2 py-1 hover:bg-blue-200 text-gray-500 hover:text-gray-800">
                                        <a class=""
                                           href="{{route('category.show', $category->slug)}}"
                                        >
                                            {{$category->title}}</a>
                                    </div>
                                </li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            @endforeach
        </div>
        <div class="bg-white px-4 py-3  justify-between border-t border-gray-200 sm:px-6 sm:rounded-b-lg">
            {{ $posts->links() }}
        </div>


    </div>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mx-auto px-4">
        <div class="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-xl rounded-lg -mt-64">
            <div class="px-6">
                <div class="flex flex-wrap justify-start">
                    <div class="w-full lg:w-2/12 px-4 -mb-12">
                        <div class="py-6 px-3 mt-32 sm:mt-0">
                            <a href="{{ url()->previous() }}"
                               class="w-full block ring-2 ring-indigo-500 active:bg-pink-600 px-2 py-1 bg-white text-center text-black hover:shadow-md hover:bg-indigo-500 hover:text-white shadow rounded outline-none focus:outline-none sm:mr-2 mb-1"
                               type="button">
                                Back
                            </a>
                        </div>
                    </div>
                </div>
                <div class="text-center mt-12"><h3
                        class="text-4xl font-semibold leading-normal mb-2 text-gray-800 mb-2">
                        {{$post->title}}
                    </h3>
                    <div class="mb-2 text-gray-700 mt-10">
                        {{$post->author->name}}
                    </div>
                </div>
                <div class="mt-10 py-10 border-t border-gray-300 text-center">
                    <div class="flex flex-wrap justify-center">
                        <div class="w-full lg:w-9/12 px-4">
                            <p class="mb-4 text-lg leading-relaxed text-gray-800">
                                {{$post->body}}
                            </p></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection